services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app/build
    command: >
      bash -c "
        cmake .. && 
        make &&
        mkdir -p /app/resources/temp &&
        cp -L lib/libred_api.so.1.0 /app/resources/temp/ &&
        cp -L _deps/json-c-build/libjson-c.so.5.3.0 /app/resources/temp/ &&
        echo 'Copying required files...' &&
        cd /app/resources/temp &&
        ln -sf libred_api.so.1.0 libred_api.so.1 &&
        ln -sf libjson-c.so.5.3.0 libjson-c.so.5 &&
        echo 'Contents of new build:' &&
        ls -la
      "